
import { Geist, Geist_Mono } from "next/font/google";
import Header from '../components/Header/page';
import Footer from '../components/Footer/page';
import ReduxProvider from "./providers/ReduxProvider";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cloud Installer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ReduxProvider>
          <Toaster position="top-right" />
            <Header/>
            {children}
            
          <Footer/>
        </ReduxProvider>
        
      
        
      </body>
    </html>
  );
}
